### ISSUE TITLE
Keyboard shortcuts don't work

### ISSUE THREAD

**Issue by ocean-haiyang** [sysadminsmedia/homebox#634]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

latest

### What is the issue you are experiencing?

Keyboard shortcut's don't work

### How can the maintainer reproduce the issue?

I am using it on firefox on linux. Tried my homebox and the demo.

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)

**Comment by tankerkiller125** [comment]
I'm unable to replicate this (the `` Ctrl+` ``) works, and hitting a number after works as expected. However I did encounter a different issue which might be a Z-Index issue.

![Image](https://github.com/user-attachments/assets/e3b69ef8-f997-4018-ad4e-91efa1c09ddb)

Thoughts @tonyaellie ?

**Comment by tonyaellie** [comment]
I also cannot replicate the issue with firefox. As for the issue with cut off this is fixed in [nightly](https://nightly.homebox.software/home) (its basically been completely cut off), note it does have an issue with blurry text that im aware of and working on a fix for.

**Comment by tonyaellie** [comment]
@EdWorth120 could you test if you still have the cpu spike with https://github.com/sysadminsmedia/homebox/pull/628

**Comment by EdWorth120** [comment]
@tonyaellie I'm having problems with errors since npx was substituted by pnpm.
Like this when the task go:run run the task typescript-types:

...
panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parking_lot_core-0.9.9/src/thread_parker/wasm.rs:26:9:
Parking not supported on this platform
...

**Comment by tankerkiller125** [comment]
Delete the `node_modules` directory and re-run `task setup` should resolve any issues related to that switch over.

**Comment by EdWorth120** [comment]
@tankerkiller125 all modules was downloaded again the directory node_modules was rebuilt but the same problem remains

**Comment by EdWorth120** [comment]
@tonyaellie yes with #628 solved the CPU spike
