### ISSUE TITLE
Unable to open attachment

### ISSUE THREAD

**Issue by tomyan112** [sysadminsmedia/homebox#833]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

0.20.2

### What is the issue you are experiencing?

Error shows when I open a location page with attachment
I have already generated thumbnails using the generate thumbnails button in "Tools" section.

![Image](https://github.com/user-attachments/assets/a24daecb-62c1-4c51-8155-b9a0a2907829)

10:42AM ERR /workspaces/homebox/backend/internal/web/mid/errors.go:31 > ERROR occurred error="open blob.Bucket: parse \"file://C:\\\\Users\\\\Tom\\\\OneDrive\\\\Homebox?no_tmp_dir=true\": invalid port \":\\\\Users\\\\Tom\\\\OneDrive\\\\Homebox\" after host" req_id=HX77G/RFCXyANnpp-000191

![Image](https://github.com/user-attachments/assets/712f97b5-16d6-47e1-805f-4840c5d23b47)

![Image](https://github.com/user-attachments/assets/179e2064-49fd-458d-9125-143fb5769130)

### How can the maintainer reproduce the issue?

open a location page with attachment

### Deployment

Other

### OS Architechture

x86_64 (AMD, Intel)

**Comment by katosdev** [comment]
@tankerkiller125 - is this related to the one that you were looking into yesterday sorry, or am I getting confused?

**Comment by murk-sy** [comment]
Same issue here after upgrading to 0.20.0, Windows x64

In browser error with paths removed:
```
{"error":"open blob.Bucket: parse \"file://E:\\\\filepath1\\\\filepath2?no_tmp_dir=true\": invalid port \":\\\\filepath1\\\\filepath2\" after host"}
```

**Comment by tankerkiller125** [comment]
@katosdev different issue.

**Comment by tankerkiller125** [comment]
Try setting the storage string to be `file:///C:/your/path/to/data?no_tmp_dir=true`

What it looks like is that Go is doing some weird path stuff on Windows.

**Comment by cxandy** [comment]
windows:
9:16PM ERR /workspaces/homebox/backend/internal/data/repo/repo_item_attachments.go:753 > failed to open bucket error="open blob.Bucket: parse \"file://D:\\\\homebox_0.20?no_tmp_dir=true\": invalid port \":\\\\homebox_0.20\" after host"

**Comment by tankerkiller125** [comment]
@cxandy see my previouys comment.

Basically try `file:///C:/your/path/to/data?no_tmp_dir=true`, not that all of the slashes must be of the `/` type, not `\`.

**Comment by murk-sy** [comment]
Tested above on 0.20.2, no dice

Returns the following regardless of actual path entered or the slash combo used or quote marks used.
Originally set up without a specific path (or to be more precise, the path is the working directory: E:\filepath1\filepath2\homebox.exe)

```powershell
.\homebox.exe --storage-prefix-path file:///E://Completelydifferentpath?no_tmp_dir=true
12:02PM FTL /workspaces/homebox/backend/app/api/main.go:135 > failed to create data directory error="mkdir E:\\filepath1\\filepath2\\file:: The filename, directory name, or volume label syntax is incorrect."

```

**Comment by tankerkiller125** [comment]
I'm still working on this issue, it's the last bug I want to sort before releasing a new bug patch release. I'm having some difficutly with it though (especially since I have to run Windows as a VM slowing some things down)

**Comment by tankerkiller125** [comment]
This issue is in theory fixed with the linked PR (#917) if you want to try it via compiling yourself for Windows, if needed I can also create a build and link it here.

**Comment by tomyan112** [comment]
> This issue is in theory fixed with the linked PR ([#917](https://github.com/sysadminsmedia/homebox/pull/917)) if you want to try it via compiling yourself for Windows, if needed I can also create a build and link it here.

It is still not working in v0.21.0

**Comment by tankerkiller125** [comment]
@tomyan112 looking at your original screenshots it looks like you put Homebox in a OneDrive directoy, please try running Homebox outside a OneDrive directory, OneDrive does weird things that are most likely incompatible with the way Homebox works.

**Comment by tomyan112** [comment]
> [@tomyan112](https://github.com/tomyan112) looking at your original screenshots it looks like you put Homebox in a OneDrive directoy, please try running Homebox outside a OneDrive directory, OneDrive does weird things that are most likely incompatible with the way Homebox works.


I've tried running Homebox outside a OneDrive directory. It is still not working.
<img width="932" height="1003" alt="Image" src="https://github.com/user-attachments/assets/8f352b4a-9a62-40a6-8edc-418b3fc4d2a4" />

**Comment by murk-sy** [comment]
Can confirm still not working
> {"error":"blob (key \".data\\\\fe0597f1-217d-4f54-a47c-fd433e1ab86b\\\\documents\\\\27b8d34b0ecb7cedf514af6f7a4722fe65d33cae2775d7f5982ce3e3c5de383e\") (code=NotFound): CreateFile E:\\path1\\path2\\.data__0x5c__fe0597f1-217d-4f54-a47c-fd433e1ab86b__0x5c__documents__0x5c__27b8d34b0ecb7cedf514af6f7a4722fe65d33cae2775d7f5982ce3e3c5de383e: The system cannot find the file specified."}


For reference, correct path to file is
`E:\path1\path2\.data\fe0597f1-217d-4f54-a47c-fd433e1ab86b\documents\27b8d34b0ecb7cedf514af6f7a4722fe65d33cae2775d7f5982ce3e3c5de383e`

**Comment by S3rrrjjj** [comment]
And new attachments are saved in the root folder (C:\path1\HomeBox\ in my case) instead of the .data folder (C:\path1\HomeBox\.data\long-installation-number\documents in my case)

New attachments file names contain the expected saving path but \ are replaced by __0x5c__

File name looks like this:  .data__0x5c__long-installation-number__0x5c__documents__0x5c__00d4f83ef299096fdeddb8ec770c2315b6185f33b3a88868c451bf58622a87a9

New attachments are displayed in the app. Old ones cannot be found.

**Comment by tomyan112** [comment]
<img width="1072" height="622" alt="Image" src="https://github.com/user-attachments/assets/6063ca96-781a-41ec-914a-80c2f39196c3" />
The existing attachments still not working in v0.22.0-rc.2.

**Comment by tonyaellie** [comment]
@tomyan112 are you able to recreate this issue on latest?

**Comment by tomyan112** [comment]
> [@tomyan112](https://github.com/tomyan112) are you able to recreate this issue on latest?

same issue exists on v0.21.0

**Comment by tankerkiller125** [comment]
This issue should now actually be fixed with #1144 getting merged based on testing and validation.

**Comment by tomyan112** [comment]
> This issue should now actually be fixed with [#1144](https://github.com/sysadminsmedia/homebox/pull/1144) getting merged based on testing and validation.

I am now on version 0.22.3. The attachments can now be opened.

Some of the file extension of the files in the database is now removed. Some still retains the file extension. Is this the expected behaviour?
<img width="547" height="376" alt="Image" src="https://github.com/user-attachments/assets/35f74f90-413b-4396-9a4b-7a43ebdcf275" />

**Comment by tankerkiller125** [comment]
The removal of file extensions in the actual stored files is expected, that was a change made with the storage provider system. Basically allows for de-duplication of file uploads. Downloading the file from Homebox will still have the correct file name and extension and what not.
